"""add date_of_birth to user_profiles

Revision ID: 408551da4bbe
Revises: b600ea16d9ae
Create Date: 2025-12-26 14:12:19.891992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408551da4bbe'
down_revision: Union[str, Sequence[str], None] = 'b600ea16d9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_of_birth')
    # ### end Alembic commands ###
