"""sync models

Revision ID: 5ec5a7942a15
Revises: ae5baa1f354e
Create Date: 2025-12-16 18:16:25.967277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ec5a7942a15'
down_revision: Union[str, Sequence[str], None] = 'ae5baa1f354e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    user_role_enum = postgresql.ENUM(
        'USER',
        'ADMIN',
        'MODERATOR',
        'MENTOR',
        name='user_role_enum'
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum(
                'USER',
                'ADMIN',
                'MODERATOR',
                'MENTOR',
                name='user_role_enum'
            ),
            nullable=True
        )
    )
    op.execute(
        """
        UPDATE users
        SET role = 'USER'
        WHERE role IS NULL
        """
    )
    op.alter_column(
        'users',
        'role',
        nullable=False,
        server_default='USER'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
