"""add new tables education, experience, certificate

Revision ID: 89cd0994c37e
Revises: 408551da4bbe
Create Date: 2025-12-26 16:18:55.998606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cd0994c37e'
down_revision: Union[str, Sequence[str], None] = '408551da4bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_certificates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificates_id'), 'user_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_user_certificates_user_id'), 'user_certificates', ['user_id'], unique=False)
    op.create_table('user_educations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_educations_id'), 'user_educations', ['id'], unique=False)
    op.create_index(op.f('ix_user_educations_user_id'), 'user_educations', ['user_id'], unique=False)
    op.create_table('user_experiences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_experiences_id'), 'user_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_user_experiences_user_id'), 'user_experiences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_experiences_user_id'), table_name='user_experiences')
    op.drop_index(op.f('ix_user_experiences_id'), table_name='user_experiences')
    op.drop_table('user_experiences')
    op.drop_index(op.f('ix_user_educations_user_id'), table_name='user_educations')
    op.drop_index(op.f('ix_user_educations_id'), table_name='user_educations')
    op.drop_table('user_educations')
    op.drop_index(op.f('ix_user_certificates_user_id'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_id'), table_name='user_certificates')
    op.drop_table('user_certificates')
    # ### end Alembic commands ###
