"""feat user_image table

Revision ID: b600ea16d9ae
Revises: bc709a27698a
Create Date: 2025-12-21 17:20:09.177732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b600ea16d9ae'
down_revision: Union[str, Sequence[str], None] = 'bc709a27698a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('avatar', 'portfolio', name='user_image_type_enum'), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('thumb_small_url', sa.String(), nullable=True),
    sa.Column('thumb_medium_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_images_id'), 'user_images', ['id'], unique=False)
    op.create_index(op.f('ix_user_images_user_id'), 'user_images', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('avatar_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'user_images', ['avatar_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'avatar_image_id')
    op.drop_index(op.f('ix_user_images_user_id'), table_name='user_images')
    op.drop_index(op.f('ix_user_images_id'), table_name='user_images')
    op.drop_table('user_images')
    # ### end Alembic commands ###
