"""fix field category_id

Revision ID: bc709a27698a
Revises: 03aea1843915
Create Date: 2025-12-18 18:37:08.310519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc709a27698a'
down_revision: Union[str, Sequence[str], None] = '03aea1843915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
