"""add new field updated_at

Revision ID: f42eeed77b86
Revises: 19f3395b7f2e
Create Date: 2025-11-15 14:39:27.914577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42eeed77b86'
down_revision: Union[str, Sequence[str], None] = '19f3395b7f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_accounts', 'updated_at')
    # ### end Alembic commands ###
