"""fix user_profile pk filed

Revision ID: fd4119bcfb64
Revises: d99d3bfbb2b9
Create Date: 2025-12-13 08:48:56.219602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4119bcfb64'
down_revision: Union[str, Sequence[str], None] = 'd99d3bfbb2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    # ### end Alembic commands ###
